SESSION_USER_ID = "user_id"
SESSION_SHOULD_DISPLAY_LOGIN = "should_display_login_success"
SESSION_SHOULD_DISPLAY_LOGOUT = "should_display_logout_message"
SESSION_SHOULD_EXPLORE_PLAYLIST = "should_explore_playlist"
SESSION_SHOULD_DISPLAY_MUSIC_ADDED = "should_display_music_added_message"
SESSION_CLEAR_SEARCH_RESULTS = "should_clear_search_results"